
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/fsm 

module dffs_WIDTH3(d, q, en, clk, rst);
  input [2:0] d;
  input en, clk, rst;
  output [2:0] q;
  wire [2:0] d;
  wire en, clk, rst;
  wire [2:0] q;
  wire n_0, n_1, n_2;
  DFFRHQX1 \q_reg[0] (.RN (n_0), .CK (clk), .D (n_2), .Q (q[0]));
  DFFRHQX1 \q_reg[1] (.RN (n_0), .CK (clk), .D (n_1), .Q (q[1]));
  SDFFRHQX1 \q_reg[2] (.RN (n_0), .CK (clk), .D (q[2]), .SI (d[2]), .SE
       (en), .Q (q[2]));
  MX2X1 g57(.A (q[0]), .B (d[0]), .S0 (en), .Y (n_2));
  MX2X1 g58(.A (q[1]), .B (d[1]), .S0 (en), .Y (n_1));
  INVX1 g59(.A (rst), .Y (n_0));
endmodule

module countdown(clk, reset, wait_cycles, write_enable,
     countdown_enable, done);
  input clk, reset, write_enable, countdown_enable;
  input [8:0] wait_cycles;
  output done;
  wire clk, reset, write_enable, countdown_enable;
  wire [8:0] wait_cycles;
  wire done;
  wire [8:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_49, n_50;
  wire n_51, n_57, n_72, n_73;
  NOR4X1 g374(.A (count[5]), .B (count[4]), .C (count[7]), .D (n_51),
       .Y (done));
  NAND2XL g375(.A (n_49), .B (n_50), .Y (n_51));
  NOR4X1 g376(.A (count[0]), .B (count[1]), .C (count[2]), .D
       (count[8]), .Y (n_50));
  NOR2XL g377(.A (count[3]), .B (count[6]), .Y (n_49));
  INVX1 g378(.A (count[7]), .Y (n_57));
  DFFHQX1 \count_reg[8] (.CK (clk), .D (n_72), .Q (count[8]));
  DFFHQX1 \count_reg[7] (.CK (clk), .D (n_47), .Q (count[7]));
  DFFHQX1 \count_reg[5] (.CK (clk), .D (n_45), .Q (count[5]));
  OAI222XL g825(.A0 (n_8), .A1 (n_40), .B0 (n_6), .B1 (n_38), .C0
       (count[7]), .C1 (n_39), .Y (n_47));
  XNOR2X1 g826(.A (wait_cycles[8]), .B (n_37), .Y (n_46));
  OAI22XL g827(.A0 (n_6), .A1 (n_42), .B0 (n_8), .B1 (n_24), .Y (n_45));
  DFFHQX1 \count_reg[4] (.CK (clk), .D (n_43), .Q (count[4]));
  DFFHQX1 \count_reg[6] (.CK (clk), .D (n_44), .Q (count[6]));
  OAI221X1 g830(.A0 (n_8), .A1 (n_30), .B0 (n_6), .B1 (n_35), .C0
       (n_39), .Y (n_44));
  OAI22XL g831(.A0 (n_6), .A1 (n_34), .B0 (n_8), .B1 (n_19), .Y (n_43));
  XNOR2X1 g832(.A (count[5]), .B (n_32), .Y (n_42));
  OAI2BB1X1 g833(.A0N (n_57), .A1N (n_36), .B0 (count[8]), .Y (n_41));
  AOI21XL g834(.A0 (wait_cycles[7]), .A1 (n_29), .B0 (n_37), .Y (n_40));
  DFFQXL \count_reg[3] (.CK (clk), .D (n_33), .Q (count[3]));
  NAND2XL g836(.A (n_5), .B (n_36), .Y (n_39));
  NAND2BXL g837(.AN (n_36), .B (count[7]), .Y (n_38));
  NOR2XL g838(.A (wait_cycles[7]), .B (n_29), .Y (n_37));
  NOR2XL g839(.A (count[6]), .B (n_73), .Y (n_36));
  NAND2XL g840(.A (count[6]), .B (n_73), .Y (n_35));
  AOI21XL g841(.A0 (count[4]), .A1 (n_25), .B0 (n_32), .Y (n_34));
  OAI22XL g842(.A0 (n_6), .A1 (n_27), .B0 (n_8), .B1 (n_14), .Y (n_33));
  NOR2XL g843(.A (count[4]), .B (n_25), .Y (n_32));
  AOI21XL g845(.A0 (wait_cycles[6]), .A1 (n_23), .B0 (n_28), .Y (n_30));
  DFFHQX1 \count_reg[2] (.CK (clk), .D (n_26), .Q (count[2]));
  INVX1 g847(.A (n_28), .Y (n_29));
  NOR2XL g848(.A (wait_cycles[6]), .B (n_23), .Y (n_28));
  OA21X1 g849(.A0 (n_2), .A1 (n_20), .B0 (n_25), .Y (n_27));
  OAI22XL g850(.A0 (n_6), .A1 (n_22), .B0 (n_10), .B1 (n_8), .Y (n_26));
  NAND2XL g851(.A (n_2), .B (n_20), .Y (n_25));
  OA21X1 g852(.A0 (n_0), .A1 (n_18), .B0 (n_23), .Y (n_24));
  DFFHQX1 \count_reg[1] (.CK (clk), .D (n_21), .Q (count[1]));
  NAND2XL g854(.A (n_0), .B (n_18), .Y (n_23));
  AOI21XL g855(.A0 (count[2]), .A1 (n_15), .B0 (n_20), .Y (n_22));
  OAI22XL g856(.A0 (n_6), .A1 (n_16), .B0 (wait_cycles[1]), .B1 (n_8),
       .Y (n_21));
  NOR2XL g857(.A (count[2]), .B (n_15), .Y (n_20));
  AOI21XL g858(.A0 (wait_cycles[4]), .A1 (n_13), .B0 (n_18), .Y (n_19));
  DFFHQX1 \count_reg[0] (.CK (clk), .D (n_17), .Q (count[0]));
  NOR2XL g860(.A (wait_cycles[4]), .B (n_13), .Y (n_18));
  OAI21XL g861(.A0 (reset), .A1 (n_12), .B0 (n_8), .Y (n_17));
  OA21X1 g862(.A0 (n_1), .A1 (n_11), .B0 (n_15), .Y (n_16));
  NAND2XL g863(.A (n_1), .B (n_11), .Y (n_15));
  OA21X1 g864(.A0 (n_3), .A1 (n_7), .B0 (n_13), .Y (n_14));
  NAND2XL g865(.A (n_3), .B (n_7), .Y (n_13));
  AOI21XL g866(.A0 (count[0]), .A1 (n_4), .B0 (n_11), .Y (n_12));
  NOR2XL g867(.A (count[0]), .B (n_4), .Y (n_11));
  AOI21XL g868(.A0 (wait_cycles[1]), .A1 (wait_cycles[2]), .B0 (n_7),
       .Y (n_10));
  NAND2BXL g870(.AN (reset), .B (write_enable), .Y (n_8));
  NOR2XL g871(.A (wait_cycles[1]), .B (wait_cycles[2]), .Y (n_7));
  INVX1 g872(.A (n_5), .Y (n_6));
  NOR2XL g873(.A (reset), .B (write_enable), .Y (n_5));
  NAND2BXL g874(.AN (done), .B (countdown_enable), .Y (n_4));
  INVX1 g875(.A (wait_cycles[3]), .Y (n_3));
  INVX1 g876(.A (count[3]), .Y (n_2));
  INVX1 g877(.A (count[1]), .Y (n_1));
  INVX1 g878(.A (wait_cycles[5]), .Y (n_0));
  OAI22X1 g2(.A0 (n_8), .A1 (n_46), .B0 (n_6), .B1 (n_41), .Y (n_72));
  OR3XL g879(.A (n_25), .B (count[5]), .C (count[4]), .Y (n_73));
endmodule

module aperture_decoder(input_setting, output_multiplier);
  input [2:0] input_setting;
  output [7:0] output_multiplier;
  wire [2:0] input_setting;
  wire [7:0] output_multiplier;
  wire n_0, n_1, n_2, n_3, n_4;
  NOR2BX1 g147(.AN (n_4), .B (input_setting[0]), .Y
       (output_multiplier[7]));
  AND2X1 g148(.A (n_4), .B (input_setting[0]), .Y
       (output_multiplier[6]));
  NOR2X1 g149(.A (input_setting[0]), .B (n_1), .Y
       (output_multiplier[1]));
  NOR2XL g150(.A (n_0), .B (n_1), .Y (output_multiplier[0]));
  NOR2XL g151(.A (n_0), .B (n_3), .Y (output_multiplier[4]));
  NOR2X1 g152(.A (input_setting[0]), .B (n_2), .Y
       (output_multiplier[3]));
  NOR2XL g153(.A (n_0), .B (n_2), .Y (output_multiplier[2]));
  NOR2X1 g154(.A (input_setting[0]), .B (n_3), .Y
       (output_multiplier[5]));
  NOR2XL g155(.A (input_setting[2]), .B (input_setting[1]), .Y (n_4));
  NAND2BXL g156(.AN (input_setting[2]), .B (input_setting[1]), .Y
       (n_3));
  NAND2BXL g157(.AN (input_setting[1]), .B (input_setting[2]), .Y
       (n_2));
  NAND2XL g158(.A (input_setting[1]), .B (input_setting[2]), .Y (n_1));
  INVX1 g159(.A (input_setting[0]), .Y (n_0));
endmodule

module shutter_decoder(input_setting, shutter_wait_time);
  input [2:0] input_setting;
  output [7:0] shutter_wait_time;
  wire [2:0] input_setting;
  wire [7:0] shutter_wait_time;
  wire n_0, n_1, n_2, n_3, n_4;
  NOR2BX1 g147(.AN (n_4), .B (input_setting[0]), .Y
       (shutter_wait_time[7]));
  AND2X1 g148(.A (n_4), .B (input_setting[0]), .Y
       (shutter_wait_time[6]));
  NOR2XL g149(.A (input_setting[0]), .B (n_1), .Y
       (shutter_wait_time[1]));
  NOR2X1 g150(.A (n_0), .B (n_1), .Y (shutter_wait_time[0]));
  NOR2X1 g151(.A (n_0), .B (n_3), .Y (shutter_wait_time[4]));
  NOR2XL g152(.A (input_setting[0]), .B (n_2), .Y
       (shutter_wait_time[3]));
  NOR2X1 g153(.A (n_0), .B (n_2), .Y (shutter_wait_time[2]));
  NOR2XL g154(.A (input_setting[0]), .B (n_3), .Y
       (shutter_wait_time[5]));
  NOR2XL g155(.A (input_setting[2]), .B (input_setting[1]), .Y (n_4));
  NAND2BXL g156(.AN (input_setting[2]), .B (input_setting[1]), .Y
       (n_3));
  NAND2BXL g157(.AN (input_setting[1]), .B (input_setting[2]), .Y
       (n_2));
  NAND2XL g158(.A (input_setting[1]), .B (input_setting[2]), .Y (n_1));
  INVX1 g159(.A (input_setting[0]), .Y (n_0));
endmodule

module dffs_WIDTH3_61(d, q, en, clk, rst);
  input [2:0] d;
  input en, clk, rst;
  output [2:0] q;
  wire [2:0] d;
  wire en, clk, rst;
  wire [2:0] q;
  wire n_0, n_1, n_2;
  DFFRHQX1 \q_reg[0] (.RN (n_0), .CK (clk), .D (n_2), .Q (q[0]));
  DFFRHQX1 \q_reg[1] (.RN (n_0), .CK (clk), .D (n_1), .Q (q[1]));
  SDFFRHQX1 \q_reg[2] (.RN (n_0), .CK (clk), .D (q[2]), .SI (d[2]), .SE
       (en), .Q (q[2]));
  MX2X1 g57(.A (q[0]), .B (d[0]), .S0 (en), .Y (n_2));
  MX2X1 g58(.A (q[1]), .B (d[1]), .S0 (en), .Y (n_1));
  INVX1 g59(.A (rst), .Y (n_0));
endmodule

module mult_unsigned(A, B, Z);
  input [15:0] A;
  input [7:0] B;
  output [15:0] Z;
  wire [15:0] A;
  wire [7:0] B;
  wire [15:0] Z;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_229, n_230, n_232;
  wire n_233, n_235, n_236, n_238, n_239, n_241, n_242, n_244;
  wire n_245, n_247, n_248;
  XNOR2X1 g2332(.A (n_225), .B (n_247), .Y (Z[14]));
  INVX1 g2333(.A (n_248), .Y (Z[13]));
  ADDFX1 g2334(.A (n_221), .B (n_220), .CI (n_244), .CO (n_247), .S
       (n_248));
  INVX1 g2335(.A (n_245), .Y (Z[12]));
  ADDFX1 g2336(.A (n_217), .B (n_222), .CI (n_241), .CO (n_244), .S
       (n_245));
  INVX1 g2337(.A (n_242), .Y (Z[11]));
  ADDFX1 g2338(.A (n_223), .B (n_218), .CI (n_238), .CO (n_241), .S
       (n_242));
  INVX1 g2339(.A (n_239), .Y (Z[10]));
  ADDFX1 g2340(.A (n_211), .B (n_224), .CI (n_235), .CO (n_238), .S
       (n_239));
  INVX1 g2341(.A (n_236), .Y (Z[9]));
  ADDFX1 g2342(.A (n_209), .B (n_212), .CI (n_232), .CO (n_235), .S
       (n_236));
  INVX1 g2343(.A (n_233), .Y (Z[8]));
  ADDFX1 g2344(.A (n_207), .B (n_210), .CI (n_229), .CO (n_232), .S
       (n_233));
  INVX1 g2345(.A (n_230), .Y (Z[7]));
  ADDFX1 g2346(.A (n_193), .B (n_208), .CI (n_226), .CO (n_229), .S
       (n_230));
  INVX1 g2347(.A (n_227), .Y (Z[6]));
  ADDFX1 g2348(.A (n_181), .B (n_194), .CI (n_214), .CO (n_226), .S
       (n_227));
  XNOR2X1 g2349(.A (n_219), .B (n_213), .Y (n_225));
  ADDFX1 g2350(.A (n_188), .B (n_176), .CI (n_196), .CO (n_223), .S
       (n_224));
  ADDFX1 g2351(.A (n_180), .B (n_199), .CI (n_202), .CO (n_221), .S
       (n_222));
  ADDFX1 g2352(.A (n_178), .B (n_201), .CI (n_198), .CO (n_219), .S
       (n_220));
  ADDFX1 g2353(.A (n_186), .B (n_187), .CI (n_200), .CO (n_217), .S
       (n_218));
  INVX1 g2354(.A (n_215), .Y (Z[5]));
  ADDFX1 g2355(.A (n_168), .B (n_182), .CI (n_204), .CO (n_214), .S
       (n_215));
  XNOR2X1 g2356(.A (n_197), .B (n_203), .Y (n_213));
  ADDFX1 g2357(.A (n_173), .B (n_183), .CI (n_189), .CO (n_211), .S
       (n_212));
  ADDFX1 g2358(.A (n_164), .B (n_170), .CI (n_174), .CO (n_209), .S
       (n_210));
  ADDFX1 g2359(.A (n_148), .B (n_161), .CI (n_171), .CO (n_207), .S
       (n_208));
  INVX1 g2360(.A (n_205), .Y (Z[4]));
  ADDFX1 g2361(.A (n_144), .B (n_190), .CI (n_169), .CO (n_204), .S
       (n_205));
  XNOR2X1 g2362(.A (n_160), .B (n_195), .Y (n_203));
  ADDFX1 g2363(.A (n_151), .B (n_155), .CI (n_185), .CO (n_201), .S
       (n_202));
  ADDFX1 g2364(.A (n_150), .B (n_158), .CI (n_175), .CO (n_199), .S
       (n_200));
  ADDFX1 g2365(.A (n_153), .B (n_157), .CI (n_179), .CO (n_197), .S
       (n_198));
  XNOR2X1 g2366(.A (n_156), .B (n_184), .Y (n_196));
  XNOR2X1 g2367(.A (n_177), .B (n_172), .Y (n_195));
  ADDFX1 g2368(.A (n_145), .B (n_122), .CI (n_162), .CO (n_193), .S
       (n_194));
  INVX1 g2369(.A (n_191), .Y (Z[3]));
  ADDFX1 g2370(.A (n_146), .B (n_114), .CI (n_165), .CO (n_190), .S
       (n_191));
  ADDFX1 g2371(.A (n_120), .B (n_131), .CI (n_163), .CO (n_188), .S
       (n_189));
  OR2X1 g2372(.A (n_156), .B (n_184), .Y (n_187));
  ADDFX1 g2373(.A (n_25), .B (n_125), .CI (n_132), .CO (n_185), .S
       (n_186));
  ADDFX1 g2374(.A (n_22), .B (n_100), .CI (n_127), .CO (n_184), .S
       (n_183));
  ADDFX1 g2375(.A (n_121), .B (n_147), .CI (n_116), .CO (n_181), .S
       (n_182));
  ADDFX1 g2376(.A (n_23), .B (n_128), .CI (n_133), .CO (n_179), .S
       (n_180));
  ADDFX1 g2377(.A (n_20), .B (n_135), .CI (n_137), .CO (n_177), .S
       (n_178));
  ADDFX1 g2378(.A (n_24), .B (n_129), .CI (n_123), .CO (n_175), .S
       (n_176));
  ADDFX1 g2379(.A (n_142), .B (n_119), .CI (n_113), .CO (n_173), .S
       (n_174));
  XNOR2X1 g2380(.A (n_152), .B (n_154), .Y (n_172));
  ADDFX1 g2381(.A (n_118), .B (n_124), .CI (n_112), .CO (n_170), .S
       (n_171));
  ADDFX1 g2382(.A (n_0), .B (n_107), .CI (n_115), .CO (n_168), .S
       (n_169));
  INVX1 g2383(.A (n_166), .Y (Z[2]));
  ADDFX1 g2384(.A (n_105), .B (n_94), .CI (n_143), .CO (n_165), .S
       (n_166));
  ADDFX1 g2385(.A (n_18), .B (n_101), .CI (n_126), .CO (n_163), .S
       (n_164));
  ADDFX1 g2386(.A (n_104), .B (n_93), .CI (n_117), .CO (n_161), .S
       (n_162));
  XNOR2X1 g2387(.A (n_141), .B (n_159), .Y (n_160));
  XNOR2X1 g2388(.A (n_21), .B (n_134), .Y (n_159));
  XNOR2X1 g2389(.A (n_96), .B (n_136), .Y (n_158));
  XNOR2X1 g2390(.A (n_99), .B (n_140), .Y (n_157));
  XNOR2X1 g2391(.A (n_95), .B (n_130), .Y (n_156));
  XNOR2X1 g2392(.A (n_98), .B (n_139), .Y (n_155));
  XNOR2X1 g2393(.A (n_97), .B (n_138), .Y (n_154));
  NAND2XL g2394(.A (n_98), .B (n_139), .Y (n_153));
  NAND2XL g2395(.A (n_99), .B (n_140), .Y (n_152));
  NAND2XL g2396(.A (n_96), .B (n_136), .Y (n_151));
  NAND2XL g2397(.A (n_95), .B (n_130), .Y (n_150));
  XNOR2X1 g2398(.A (n_88), .B (n_102), .Y (Z[1]));
  XNOR2X1 g2399(.A (n_111), .B (n_103), .Y (n_148));
  XNOR2X1 g2400(.A (n_110), .B (n_108), .Y (n_147));
  XNOR2X1 g2401(.A (n_109), .B (n_106), .Y (n_146));
  OR2X1 g2402(.A (n_110), .B (n_108), .Y (n_145));
  OR2X1 g2403(.A (n_109), .B (n_106), .Y (n_144));
  NAND2BXL g2404(.AN (n_88), .B (n_102), .Y (n_143));
  OR2X1 g2405(.A (n_111), .B (n_103), .Y (n_142));
  OAI22XL g2406(.A0 (n_68), .A1 (n_91), .B0 (n_66), .B1 (n_75), .Y
       (n_141));
  OAI22XL g2407(.A0 (n_70), .A1 (n_89), .B0 (n_74), .B1 (n_83), .Y
       (n_140));
  OAI22XL g2408(.A0 (n_72), .A1 (n_89), .B0 (n_70), .B1 (n_83), .Y
       (n_139));
  OAI22XL g2409(.A0 (n_74), .A1 (n_89), .B0 (n_73), .B1 (n_83), .Y
       (n_138));
  OA22X1 g2410(.A0 (n_58), .A1 (n_91), .B0 (n_68), .B1 (n_75), .Y
       (n_137));
  OAI22XL g2411(.A0 (n_60), .A1 (n_89), .B0 (n_72), .B1 (n_83), .Y
       (n_136));
  AOI22XL g2412(.A0 (n_34), .A1 (n_92), .B0 (n_57), .B1 (n_69), .Y
       (n_135));
  AO22X1 g2413(.A0 (n_57), .A1 (n_92), .B0 (n_56), .B1 (n_69), .Y
       (n_134));
  OA22X1 g2414(.A0 (n_59), .A1 (n_91), .B0 (n_58), .B1 (n_75), .Y
       (n_133));
  OA22X1 g2415(.A0 (n_41), .A1 (n_91), .B0 (n_59), .B1 (n_75), .Y
       (n_132));
  AOI22XL g2416(.A0 (n_48), .A1 (n_90), .B0 (n_61), .B1 (n_82), .Y
       (n_131));
  OAI22XL g2417(.A0 (n_62), .A1 (n_89), .B0 (n_60), .B1 (n_83), .Y
       (n_130));
  AOI22XL g2418(.A0 (n_35), .A1 (n_92), .B0 (n_32), .B1 (n_69), .Y
       (n_129));
  AOI22XL g2419(.A0 (n_40), .A1 (n_92), .B0 (n_34), .B1 (n_69), .Y
       (n_128));
  AOI22XL g2420(.A0 (n_38), .A1 (n_92), .B0 (n_35), .B1 (n_69), .Y
       (n_127));
  AOI22XL g2421(.A0 (n_36), .A1 (n_92), .B0 (n_38), .B1 (n_69), .Y
       (n_126));
  AOI22XL g2422(.A0 (n_32), .A1 (n_92), .B0 (n_40), .B1 (n_69), .Y
       (n_125));
  AOI22XL g2423(.A0 (n_29), .A1 (n_92), .B0 (n_36), .B1 (n_69), .Y
       (n_124));
  OA22X1 g2424(.A0 (n_37), .A1 (n_91), .B0 (n_41), .B1 (n_75), .Y
       (n_123));
  OA22X1 g2425(.A0 (n_43), .A1 (n_91), .B0 (n_33), .B1 (n_75), .Y
       (n_122));
  OA22X1 g2426(.A0 (n_30), .A1 (n_91), .B0 (n_43), .B1 (n_75), .Y
       (n_121));
  OA22X1 g2427(.A0 (n_39), .A1 (n_91), .B0 (n_37), .B1 (n_75), .Y
       (n_120));
  OA22X1 g2428(.A0 (n_42), .A1 (n_91), .B0 (n_39), .B1 (n_75), .Y
       (n_119));
  OA22X1 g2429(.A0 (n_33), .A1 (n_91), .B0 (n_42), .B1 (n_75), .Y
       (n_118));
  AOI22XL g2430(.A0 (n_46), .A1 (n_90), .B0 (n_44), .B1 (n_82), .Y
       (n_117));
  AOI22XL g2431(.A0 (n_47), .A1 (n_90), .B0 (n_46), .B1 (n_82), .Y
       (n_116));
  AOI22XL g2432(.A0 (n_49), .A1 (n_90), .B0 (n_47), .B1 (n_82), .Y
       (n_115));
  AOI22XL g2433(.A0 (n_31), .A1 (n_90), .B0 (n_49), .B1 (n_82), .Y
       (n_114));
  AOI22XL g2434(.A0 (n_45), .A1 (n_90), .B0 (n_48), .B1 (n_82), .Y
       (n_113));
  AOI22XL g2435(.A0 (n_44), .A1 (n_90), .B0 (n_45), .B1 (n_82), .Y
       (n_112));
  OAI21XL g2436(.A0 (n_28), .A1 (n_87), .B0 (B[7]), .Y (n_111));
  OAI21XL g2437(.A0 (n_27), .A1 (n_86), .B0 (B[5]), .Y (n_110));
  OAI21XL g2438(.A0 (n_26), .A1 (n_85), .B0 (B[3]), .Y (n_109));
  AOI22XL g2439(.A0 (n_16), .A1 (n_51), .B0 (B[0]), .B1 (n_52), .Y
       (n_108));
  AOI22XL g2440(.A0 (n_16), .A1 (n_53), .B0 (B[0]), .B1 (n_51), .Y
       (n_107));
  AOI22XL g2441(.A0 (n_16), .A1 (n_54), .B0 (B[0]), .B1 (n_53), .Y
       (n_106));
  AOI22XL g2442(.A0 (n_16), .A1 (n_50), .B0 (B[0]), .B1 (n_54), .Y
       (n_105));
  AOI22XL g2443(.A0 (n_16), .A1 (n_52), .B0 (B[0]), .B1 (n_55), .Y
       (n_104));
  AOI22XL g2444(.A0 (n_16), .A1 (n_55), .B0 (B[0]), .B1 (n_63), .Y
       (n_103));
  AO22X1 g2445(.A0 (B[0]), .A1 (n_50), .B0 (n_2), .B1 (n_16), .Y
       (n_102));
  AOI22XL g2446(.A0 (n_16), .A1 (n_63), .B0 (B[0]), .B1 (n_64), .Y
       (n_101));
  AOI22XL g2447(.A0 (n_16), .A1 (n_64), .B0 (B[0]), .B1 (n_77), .Y
       (n_100));
  OAI22XL g2448(.A0 (n_17), .A1 (n_84), .B0 (n_14), .B1 (n_80), .Y
       (n_99));
  OAI22XL g2449(.A0 (n_17), .A1 (n_79), .B0 (n_14), .B1 (n_84), .Y
       (n_98));
  OA22X1 g2450(.A0 (n_17), .A1 (n_80), .B0 (n_14), .B1 (n_78), .Y
       (n_97));
  OAI22XL g2451(.A0 (n_17), .A1 (n_81), .B0 (n_14), .B1 (n_79), .Y
       (n_96));
  OAI22XL g2452(.A0 (n_17), .A1 (n_76), .B0 (n_14), .B1 (n_81), .Y
       (n_95));
  NAND2XL g2454(.A (A[0]), .B (n_82), .Y (n_94));
  NAND2XL g2455(.A (A[0]), .B (n_69), .Y (n_93));
  NOR2XL g2456(.A (n_67), .B (n_69), .Y (n_92));
  NAND2XL g2457(.A (n_75), .B (n_65), .Y (n_91));
  INVX1 g2458(.A (n_90), .Y (n_89));
  NOR2XL g2459(.A (n_71), .B (n_82), .Y (n_90));
  NAND2BXL g2460(.AN (Z[0]), .B (B[1]), .Y (n_88));
  AOI21XL g2461(.A0 (A[0]), .A1 (B[6]), .B0 (B[5]), .Y (n_87));
  AOI21XL g2462(.A0 (A[0]), .A1 (B[4]), .B0 (B[3]), .Y (n_86));
  AOI21XL g2463(.A0 (A[0]), .A1 (B[2]), .B0 (B[1]), .Y (n_85));
  XNOR2X1 g2464(.A (A[12]), .B (B[1]), .Y (n_84));
  INVX1 g2465(.A (n_83), .Y (n_82));
  XNOR2X1 g2466(.A (B[2]), .B (B[1]), .Y (n_83));
  XNOR2X1 g2467(.A (A[10]), .B (B[1]), .Y (n_81));
  XNOR2X1 g2468(.A (A[13]), .B (B[1]), .Y (n_80));
  XNOR2X1 g2469(.A (A[11]), .B (B[1]), .Y (n_79));
  XNOR2X1 g2470(.A (A[14]), .B (B[1]), .Y (n_78));
  INVX1 g2471(.A (n_76), .Y (n_77));
  XNOR2X1 g2472(.A (A[9]), .B (B[1]), .Y (n_76));
  XNOR2X1 g2474(.A (B[4]), .B (B[3]), .Y (n_75));
  XNOR2X1 g2475(.A (A[11]), .B (B[3]), .Y (n_74));
  XNOR2X1 g2476(.A (A[12]), .B (B[3]), .Y (n_73));
  XNOR2X1 g2477(.A (A[9]), .B (B[3]), .Y (n_72));
  XNOR2X1 g2478(.A (B[2]), .B (B[3]), .Y (n_71));
  XNOR2X1 g2479(.A (A[10]), .B (B[3]), .Y (n_70));
  MX2X1 g2480(.A (B[5]), .B (n_6), .S0 (B[6]), .Y (n_69));
  XNOR2X1 g2481(.A (A[9]), .B (B[5]), .Y (n_68));
  XNOR2X1 g2482(.A (B[6]), .B (B[7]), .Y (n_67));
  XNOR2X1 g2483(.A (A[10]), .B (B[5]), .Y (n_66));
  XNOR2X1 g2484(.A (B[4]), .B (n_6), .Y (n_65));
  OAI22XL g2485(.A0 (n_3), .A1 (B[1]), .B0 (A[8]), .B1 (n_9), .Y
       (n_64));
  OAI22XL g2486(.A0 (n_11), .A1 (B[1]), .B0 (A[7]), .B1 (n_9), .Y
       (n_63));
  INVX1 g2487(.A (n_61), .Y (n_62));
  OAI22XL g2488(.A0 (n_11), .A1 (B[3]), .B0 (A[7]), .B1 (n_15), .Y
       (n_61));
  AOI22XL g2489(.A0 (A[8]), .A1 (n_15), .B0 (n_3), .B1 (B[3]), .Y
       (n_60));
  AOI22XL g2490(.A0 (A[7]), .A1 (n_6), .B0 (n_11), .B1 (B[5]), .Y
       (n_59));
  AOI22XL g2491(.A0 (A[8]), .A1 (n_6), .B0 (n_3), .B1 (B[5]), .Y
       (n_58));
  OAI22XL g2492(.A0 (n_11), .A1 (B[7]), .B0 (A[7]), .B1 (n_10), .Y
       (n_57));
  OAI22XL g2493(.A0 (n_3), .A1 (B[7]), .B0 (A[8]), .B1 (n_10), .Y
       (n_56));
  OAI22XL g2494(.A0 (n_5), .A1 (B[1]), .B0 (A[6]), .B1 (n_9), .Y
       (n_55));
  OAI22XL g2495(.A0 (n_4), .A1 (B[1]), .B0 (A[2]), .B1 (n_9), .Y
       (n_54));
  OAI22XL g2496(.A0 (n_13), .A1 (B[1]), .B0 (A[3]), .B1 (n_9), .Y
       (n_53));
  OAI22XL g2497(.A0 (n_12), .A1 (B[1]), .B0 (A[5]), .B1 (n_9), .Y
       (n_52));
  OAI22XL g2498(.A0 (n_7), .A1 (B[1]), .B0 (A[4]), .B1 (n_9), .Y
       (n_51));
  OAI22XL g2499(.A0 (n_8), .A1 (B[1]), .B0 (A[1]), .B1 (n_9), .Y
       (n_50));
  OAI22XL g2500(.A0 (n_8), .A1 (B[3]), .B0 (A[1]), .B1 (n_15), .Y
       (n_49));
  OAI22XL g2501(.A0 (n_5), .A1 (B[3]), .B0 (A[6]), .B1 (n_15), .Y
       (n_48));
  OAI22XL g2502(.A0 (n_4), .A1 (B[3]), .B0 (A[2]), .B1 (n_15), .Y
       (n_47));
  OAI22XL g2503(.A0 (n_13), .A1 (B[3]), .B0 (A[3]), .B1 (n_15), .Y
       (n_46));
  OAI22XL g2504(.A0 (n_12), .A1 (B[3]), .B0 (A[5]), .B1 (n_15), .Y
       (n_45));
  OAI22XL g2505(.A0 (n_7), .A1 (B[3]), .B0 (A[4]), .B1 (n_15), .Y
       (n_44));
  AOI22XL g2506(.A0 (A[1]), .A1 (n_6), .B0 (n_8), .B1 (B[5]), .Y
       (n_43));
  AOI22XL g2507(.A0 (A[3]), .A1 (n_6), .B0 (n_13), .B1 (B[5]), .Y
       (n_42));
  AOI22XL g2508(.A0 (A[6]), .A1 (n_6), .B0 (n_5), .B1 (B[5]), .Y
       (n_41));
  OAI22XL g2509(.A0 (n_12), .A1 (B[7]), .B0 (A[5]), .B1 (n_10), .Y
       (n_40));
  AOI22XL g2510(.A0 (A[4]), .A1 (n_6), .B0 (n_7), .B1 (B[5]), .Y
       (n_39));
  OAI22XL g2511(.A0 (n_4), .A1 (B[7]), .B0 (A[2]), .B1 (n_10), .Y
       (n_38));
  AOI22XL g2512(.A0 (A[5]), .A1 (n_6), .B0 (n_12), .B1 (B[5]), .Y
       (n_37));
  OAI22XL g2513(.A0 (n_8), .A1 (B[7]), .B0 (A[1]), .B1 (n_10), .Y
       (n_36));
  OAI22XL g2514(.A0 (n_13), .A1 (B[7]), .B0 (A[3]), .B1 (n_10), .Y
       (n_35));
  OAI22XL g2515(.A0 (n_5), .A1 (B[7]), .B0 (A[6]), .B1 (n_10), .Y
       (n_34));
  AOI22XL g2516(.A0 (A[2]), .A1 (n_6), .B0 (n_4), .B1 (B[5]), .Y
       (n_33));
  OAI22XL g2517(.A0 (n_7), .A1 (B[7]), .B0 (A[4]), .B1 (n_10), .Y
       (n_32));
  OAI22XL g2518(.A0 (n_2), .A1 (B[3]), .B0 (A[0]), .B1 (n_15), .Y
       (n_31));
  AOI22XL g2519(.A0 (A[0]), .A1 (n_6), .B0 (n_2), .B1 (B[5]), .Y
       (n_30));
  OAI22XL g2520(.A0 (n_2), .A1 (B[7]), .B0 (A[0]), .B1 (n_10), .Y
       (n_29));
  NOR2XL g2521(.A (A[0]), .B (B[6]), .Y (n_28));
  NOR2XL g2522(.A (A[0]), .B (B[4]), .Y (n_27));
  NOR2XL g2523(.A (A[0]), .B (B[2]), .Y (n_26));
  NAND2XL g2524(.A (A[3]), .B (B[7]), .Y (n_25));
  NAND2XL g2525(.A (A[2]), .B (B[7]), .Y (n_24));
  NAND2XL g2526(.A (A[4]), .B (B[7]), .Y (n_23));
  NAND2XL g2527(.A (A[1]), .B (B[7]), .Y (n_22));
  NAND2XL g2528(.A (A[6]), .B (B[7]), .Y (n_21));
  NAND2XL g2529(.A (A[5]), .B (B[7]), .Y (n_20));
  NOR2X1 g2530(.A (n_2), .B (n_14), .Y (Z[0]));
  NAND2XL g2531(.A (A[0]), .B (B[7]), .Y (n_18));
  INVX1 g2532(.A (n_17), .Y (n_16));
  NAND2XL g2533(.A (B[1]), .B (n_14), .Y (n_17));
  INVX1 g2534(.A (B[3]), .Y (n_15));
  INVX1 g2535(.A (B[0]), .Y (n_14));
  INVX1 g2536(.A (A[3]), .Y (n_13));
  INVX1 g2537(.A (A[5]), .Y (n_12));
  INVX1 g2538(.A (A[7]), .Y (n_11));
  INVX1 g2539(.A (B[7]), .Y (n_10));
  INVX1 g2540(.A (B[1]), .Y (n_9));
  INVX1 g2541(.A (A[1]), .Y (n_8));
  INVX1 g2542(.A (A[4]), .Y (n_7));
  INVX1 g2543(.A (B[5]), .Y (n_6));
  INVX1 g2544(.A (A[6]), .Y (n_5));
  INVX1 g2545(.A (A[2]), .Y (n_4));
  INVX1 g2546(.A (A[8]), .Y (n_3));
  INVX1 g2547(.A (A[0]), .Y (n_2));
  NAND2BX1 g2(.AN (n_75), .B (A[0]), .Y (n_0));
  TIELO tie_0_cell(.Y (Z[15]));
endmodule

module mult_unsigned_197(A, B, Z);
  input [15:0] A;
  input [8:0] B;
  output [15:0] Z;
  wire [15:0] A;
  wire [8:0] B;
  wire [15:0] Z;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_212, n_213, n_214;
  wire n_216, n_217, n_219, n_220, n_222, n_223, n_225, n_226;
  wire n_228, n_229, n_231, n_232, n_234, n_235;
  XNOR2X1 g2342(.A (n_212), .B (n_234), .Y (Z[15]));
  INVX1 g2343(.A (n_235), .Y (Z[14]));
  ADDFX1 g2344(.A (n_205), .B (n_204), .CI (n_231), .CO (n_234), .S
       (n_235));
  INVX1 g2345(.A (n_232), .Y (Z[13]));
  ADDFX1 g2346(.A (n_201), .B (n_206), .CI (n_228), .CO (n_231), .S
       (n_232));
  INVX1 g2347(.A (n_229), .Y (Z[12]));
  ADDFX1 g2348(.A (n_199), .B (n_202), .CI (n_225), .CO (n_228), .S
       (n_229));
  INVX1 g2349(.A (n_226), .Y (Z[11]));
  ADDFX1 g2350(.A (n_207), .B (n_200), .CI (n_222), .CO (n_225), .S
       (n_226));
  INVX1 g2351(.A (n_223), .Y (Z[10]));
  ADDFX1 g2352(.A (n_193), .B (n_208), .CI (n_219), .CO (n_222), .S
       (n_223));
  INVX1 g2353(.A (n_220), .Y (Z[9]));
  ADDFX1 g2354(.A (n_185), .B (n_194), .CI (n_216), .CO (n_219), .S
       (n_220));
  INVX1 g2355(.A (n_217), .Y (Z[8]));
  ADDFX1 g2356(.A (n_191), .B (n_213), .CI (n_186), .CO (n_216), .S
       (n_217));
  INVX1 g2357(.A (n_214), .Y (Z[7]));
  ADDFX1 g2358(.A (n_175), .B (n_192), .CI (n_209), .CO (n_213), .S
       (n_214));
  XNOR2X1 g2359(.A (n_203), .B (n_195), .Y (n_212));
  INVX1 g2360(.A (n_210), .Y (Z[6]));
  ADDFX1 g2361(.A (n_161), .B (n_196), .CI (n_176), .CO (n_209), .S
       (n_210));
  ADDFX1 g2362(.A (n_170), .B (n_174), .CI (n_160), .CO (n_207), .S
       (n_208));
  ADDFX1 g2363(.A (n_183), .B (n_182), .CI (n_154), .CO (n_205), .S
       (n_206));
  ADDFX1 g2364(.A (n_181), .B (n_180), .CI (n_156), .CO (n_203), .S
       (n_204));
  ADDFX1 g2365(.A (n_177), .B (n_184), .CI (n_166), .CO (n_201), .S
       (n_202));
  ADDFX1 g2366(.A (n_173), .B (n_178), .CI (n_150), .CO (n_199), .S
       (n_200));
  INVX1 g2367(.A (n_197), .Y (Z[5]));
  ADDFX1 g2368(.A (n_142), .B (n_162), .CI (n_188), .CO (n_196), .S
       (n_197));
  XNOR2X1 g2369(.A (n_179), .B (n_187), .Y (n_195));
  ADDFX1 g2370(.A (n_163), .B (n_152), .CI (n_171), .CO (n_193), .S
       (n_194));
  ADDFX1 g2371(.A (n_157), .B (n_139), .CI (n_146), .CO (n_191), .S
       (n_192));
  INVX1 g2372(.A (n_189), .Y (Z[4]));
  ADDFX1 g2373(.A (n_132), .B (n_167), .CI (n_143), .CO (n_188), .S
       (n_189));
  XNOR2X1 g2374(.A (n_172), .B (n_144), .Y (n_187));
  ADDFX1 g2375(.A (n_145), .B (n_164), .CI (n_148), .CO (n_185), .S
       (n_186));
  ADDFX1 g2376(.A (n_105), .B (n_112), .CI (n_149), .CO (n_183), .S
       (n_184));
  ADDFX1 g2377(.A (n_111), .B (n_115), .CI (n_165), .CO (n_181), .S
       (n_182));
  ADDFX1 g2378(.A (n_116), .B (n_119), .CI (n_153), .CO (n_179), .S
       (n_180));
  ADDFX1 g2379(.A (n_108), .B (n_109), .CI (n_159), .CO (n_177), .S
       (n_178));
  ADDFX1 g2380(.A (n_134), .B (n_21), .CI (n_158), .CO (n_175), .S
       (n_176));
  ADDFX1 g2381(.A (n_107), .B (n_94), .CI (n_151), .CO (n_173), .S
       (n_174));
  XNOR2X1 g2382(.A (n_137), .B (n_155), .Y (n_172));
  ADDFX1 g2383(.A (n_124), .B (n_25), .CI (n_147), .CO (n_170), .S
       (n_171));
  INVX1 g2384(.A (n_168), .Y (Z[3]));
  ADDFX1 g2385(.A (n_136), .B (n_100), .CI (n_133), .CO (n_167), .S
       (n_168));
  ADDFX1 g2386(.A (n_125), .B (n_28), .CI (n_118), .CO (n_165), .S
       (n_166));
  ADDFX1 g2387(.A (n_104), .B (n_92), .CI (n_135), .CO (n_163), .S
       (n_164));
  ADDFX1 g2388(.A (n_95), .B (n_18), .CI (n_138), .CO (n_161), .S
       (n_162));
  ADDFX1 g2389(.A (n_128), .B (n_24), .CI (n_113), .CO (n_159), .S
       (n_160));
  ADDFX1 g2390(.A (n_86), .B (n_96), .CI (n_102), .CO (n_157), .S
       (n_158));
  ADDFX1 g2391(.A (n_129), .B (n_29), .CI (n_122), .CO (n_155), .S
       (n_156));
  ADDFX1 g2392(.A (n_127), .B (n_33), .CI (n_120), .CO (n_153), .S
       (n_154));
  ADDFX1 g2393(.A (n_106), .B (n_93), .CI (n_110), .CO (n_151), .S
       (n_152));
  ADDFX1 g2394(.A (n_126), .B (n_31), .CI (n_114), .CO (n_149), .S
       (n_150));
  ADDFX1 g2395(.A (n_85), .B (n_23), .CI (n_98), .CO (n_147), .S
       (n_148));
  ADDFX1 g2396(.A (n_103), .B (n_91), .CI (n_22), .CO (n_145), .S
       (n_146));
  XNOR2X1 g2397(.A (n_121), .B (n_140), .Y (n_144));
  ADDFX1 g2398(.A (n_0), .B (n_19), .CI (n_101), .CO (n_142), .S
       (n_143));
  XNOR2X1 g2399(.A (n_16), .B (n_131), .Y (Z[2]));
  XNOR2X1 g2400(.A (n_130), .B (n_32), .Y (n_140));
  XNOR2X1 g2401(.A (n_89), .B (n_97), .Y (n_139));
  XNOR2X1 g2402(.A (n_88), .B (n_99), .Y (n_138));
  XNOR2X1 g2403(.A (n_117), .B (n_123), .Y (n_137));
  OA22X1 g2404(.A0 (n_84), .A1 (n_17), .B0 (n_16), .B1 (n_17), .Y
       (n_136));
  OR2X1 g2405(.A (n_89), .B (n_97), .Y (n_135));
  OR2X1 g2406(.A (n_88), .B (n_99), .Y (n_134));
  XNOR2X1 g2407(.A (n_90), .B (n_20), .Y (n_133));
  OR2X1 g2408(.A (n_90), .B (n_20), .Y (n_132));
  CLKXOR2X1 g2409(.A (n_84), .B (n_17), .Y (n_131));
  AOI22XL g2410(.A0 (n_87), .A1 (A[6]), .B0 (n_65), .B1 (A[7]), .Y
       (n_130));
  AOI22XL g2411(.A0 (n_87), .A1 (A[5]), .B0 (n_65), .B1 (A[6]), .Y
       (n_129));
  AOI22XL g2412(.A0 (A[1]), .A1 (n_87), .B0 (n_65), .B1 (A[2]), .Y
       (n_128));
  AOI22XL g2413(.A0 (n_87), .A1 (A[4]), .B0 (n_65), .B1 (A[5]), .Y
       (n_127));
  AOI22XL g2414(.A0 (n_87), .A1 (A[2]), .B0 (n_65), .B1 (A[3]), .Y
       (n_126));
  AOI22XL g2415(.A0 (n_87), .A1 (A[3]), .B0 (n_65), .B1 (A[4]), .Y
       (n_125));
  AOI22XL g2416(.A0 (A[0]), .A1 (n_87), .B0 (n_65), .B1 (A[1]), .Y
       (n_124));
  OAI22XL g2417(.A0 (n_82), .A1 (n_70), .B0 (n_72), .B1 (n_68), .Y
       (n_123));
  AOI22XL g2418(.A0 (n_81), .A1 (n_76), .B0 (n_60), .B1 (n_74), .Y
       (n_122));
  AO22X1 g2419(.A0 (n_81), .A1 (n_74), .B0 (n_60), .B1 (n_73), .Y
       (n_121));
  AOI22XL g2420(.A0 (n_81), .A1 (n_75), .B0 (n_60), .B1 (n_76), .Y
       (n_120));
  OA22X1 g2421(.A0 (n_82), .A1 (n_61), .B0 (n_72), .B1 (n_70), .Y
       (n_119));
  AOI22XL g2422(.A0 (n_81), .A1 (n_63), .B0 (n_60), .B1 (n_75), .Y
       (n_118));
  AOI22XL g2423(.A0 (n_83), .A1 (n_59), .B0 (n_69), .B1 (n_58), .Y
       (n_117));
  AOI22XL g2424(.A0 (n_83), .A1 (n_55), .B0 (n_69), .B1 (n_59), .Y
       (n_116));
  OA22X1 g2425(.A0 (n_82), .A1 (n_62), .B0 (n_72), .B1 (n_61), .Y
       (n_115));
  AOI22XL g2426(.A0 (n_81), .A1 (n_64), .B0 (n_60), .B1 (n_63), .Y
       (n_114));
  AOI22XL g2427(.A0 (n_81), .A1 (n_57), .B0 (n_60), .B1 (n_64), .Y
       (n_113));
  OA22X1 g2428(.A0 (n_82), .A1 (n_56), .B0 (n_72), .B1 (n_62), .Y
       (n_112));
  AOI22XL g2429(.A0 (n_83), .A1 (n_37), .B0 (n_69), .B1 (n_55), .Y
       (n_111));
  AOI22XL g2430(.A0 (n_81), .A1 (n_52), .B0 (n_60), .B1 (n_57), .Y
       (n_110));
  OA22X1 g2431(.A0 (n_82), .A1 (n_44), .B0 (n_72), .B1 (n_56), .Y
       (n_109));
  AOI22XL g2432(.A0 (n_83), .A1 (n_40), .B0 (n_69), .B1 (n_42), .Y
       (n_108));
  AOI22XL g2433(.A0 (n_83), .A1 (n_41), .B0 (n_69), .B1 (n_40), .Y
       (n_107));
  AOI22XL g2434(.A0 (n_83), .A1 (n_38), .B0 (n_69), .B1 (n_41), .Y
       (n_106));
  AOI22XL g2435(.A0 (n_83), .A1 (n_42), .B0 (n_69), .B1 (n_37), .Y
       (n_105));
  AOI22XL g2436(.A0 (n_83), .A1 (n_39), .B0 (n_69), .B1 (n_38), .Y
       (n_104));
  AOI22XL g2437(.A0 (n_83), .A1 (n_34), .B0 (n_69), .B1 (n_39), .Y
       (n_103));
  AOI22XL g2438(.A0 (n_81), .A1 (n_51), .B0 (n_60), .B1 (n_50), .Y
       (n_102));
  AOI22XL g2439(.A0 (n_81), .A1 (n_54), .B0 (n_60), .B1 (n_53), .Y
       (n_101));
  AOI22XL g2440(.A0 (n_36), .A1 (n_81), .B0 (n_60), .B1 (n_54), .Y
       (n_100));
  AOI22XL g2441(.A0 (n_81), .A1 (n_53), .B0 (n_60), .B1 (n_51), .Y
       (n_99));
  AOI22XL g2442(.A0 (n_81), .A1 (n_49), .B0 (n_60), .B1 (n_52), .Y
       (n_98));
  AOI22XL g2443(.A0 (n_81), .A1 (n_50), .B0 (n_60), .B1 (n_49), .Y
       (n_97));
  OA22X1 g2444(.A0 (n_82), .A1 (n_46), .B0 (n_72), .B1 (n_47), .Y
       (n_96));
  OA22X1 g2445(.A0 (n_35), .A1 (n_82), .B0 (n_72), .B1 (n_46), .Y
       (n_95));
  OA22X1 g2446(.A0 (n_82), .A1 (n_48), .B0 (n_72), .B1 (n_44), .Y
       (n_94));
  OA22X1 g2447(.A0 (n_82), .A1 (n_43), .B0 (n_72), .B1 (n_48), .Y
       (n_93));
  OA22X1 g2448(.A0 (n_82), .A1 (n_45), .B0 (n_72), .B1 (n_43), .Y
       (n_92));
  OA22X1 g2449(.A0 (n_82), .A1 (n_47), .B0 (n_72), .B1 (n_45), .Y
       (n_91));
  OAI21XL g2450(.A0 (n_26), .A1 (n_79), .B0 (B[3]), .Y (n_90));
  OAI21XL g2451(.A0 (n_27), .A1 (n_78), .B0 (B[7]), .Y (n_89));
  OAI21XL g2452(.A0 (n_30), .A1 (n_77), .B0 (B[5]), .Y (n_88));
  NOR2BX1 g2453(.AN (B[8]), .B (n_65), .Y (n_87));
  NAND2XL g2454(.A (A[0]), .B (n_69), .Y (n_86));
  NAND2XL g2456(.A (A[0]), .B (n_65), .Y (n_85));
  NAND2XL g2457(.A (A[0]), .B (n_60), .Y (n_84));
  NOR2XL g2458(.A (n_66), .B (n_69), .Y (n_83));
  NAND2XL g2459(.A (n_72), .B (n_67), .Y (n_82));
  NOR2XL g2460(.A (n_71), .B (n_60), .Y (n_81));
  AND2X1 g2461(.A (n_16), .B (B[1]), .Y (Z[1]));
  AOI21XL g2462(.A0 (B[2]), .A1 (A[0]), .B0 (B[1]), .Y (n_79));
  AOI21XL g2463(.A0 (B[6]), .A1 (A[0]), .B0 (B[5]), .Y (n_78));
  AOI21XL g2464(.A0 (B[4]), .A1 (A[0]), .B0 (B[3]), .Y (n_77));
  MX2X1 g2465(.A (B[3]), .B (n_11), .S0 (A[11]), .Y (n_76));
  XNOR2X1 g2466(.A (n_11), .B (A[10]), .Y (n_75));
  XNOR2X1 g2467(.A (n_11), .B (A[12]), .Y (n_74));
  XNOR2X1 g2468(.A (n_11), .B (A[13]), .Y (n_73));
  XNOR2X1 g2470(.A (B[4]), .B (B[3]), .Y (n_72));
  XNOR2X1 g2471(.A (B[2]), .B (B[3]), .Y (n_71));
  XNOR2X1 g2472(.A (B[5]), .B (A[10]), .Y (n_70));
  MX2X1 g2473(.A (B[5]), .B (n_5), .S0 (B[6]), .Y (n_69));
  XNOR2X1 g2474(.A (B[5]), .B (A[11]), .Y (n_68));
  XNOR2X1 g2475(.A (B[4]), .B (n_5), .Y (n_67));
  XNOR2X1 g2476(.A (B[6]), .B (B[7]), .Y (n_66));
  MX2X1 g2477(.A (B[7]), .B (n_12), .S0 (B[8]), .Y (n_65));
  OAI22XL g2478(.A0 (B[3]), .A1 (n_15), .B0 (n_11), .B1 (A[8]), .Y
       (n_64));
  OAI22XL g2479(.A0 (B[3]), .A1 (n_7), .B0 (n_11), .B1 (A[9]), .Y
       (n_63));
  AOI22XL g2480(.A0 (n_5), .A1 (A[8]), .B0 (B[5]), .B1 (n_15), .Y
       (n_62));
  AOI22XL g2481(.A0 (n_5), .A1 (A[9]), .B0 (B[5]), .B1 (n_7), .Y
       (n_61));
  MX2X1 g2482(.A (B[1]), .B (n_3), .S0 (B[2]), .Y (n_60));
  OAI22XL g2483(.A0 (B[7]), .A1 (n_15), .B0 (n_12), .B1 (A[8]), .Y
       (n_59));
  OAI22XL g2484(.A0 (B[7]), .A1 (n_7), .B0 (n_12), .B1 (A[9]), .Y
       (n_58));
  OAI22XL g2485(.A0 (B[3]), .A1 (n_6), .B0 (n_11), .B1 (A[7]), .Y
       (n_57));
  AOI22XL g2486(.A0 (n_5), .A1 (A[7]), .B0 (B[5]), .B1 (n_6), .Y
       (n_56));
  OAI22XL g2487(.A0 (B[7]), .A1 (n_6), .B0 (n_12), .B1 (A[7]), .Y
       (n_55));
  OAI22XL g2488(.A0 (B[3]), .A1 (n_2), .B0 (n_11), .B1 (A[1]), .Y
       (n_54));
  OAI22XL g2489(.A0 (B[3]), .A1 (n_10), .B0 (n_11), .B1 (A[2]), .Y
       (n_53));
  OAI22XL g2490(.A0 (B[3]), .A1 (n_14), .B0 (n_11), .B1 (A[6]), .Y
       (n_52));
  OAI22XL g2491(.A0 (B[3]), .A1 (n_4), .B0 (n_11), .B1 (A[3]), .Y
       (n_51));
  OAI22XL g2492(.A0 (B[3]), .A1 (n_9), .B0 (n_11), .B1 (A[4]), .Y
       (n_50));
  OAI22XL g2493(.A0 (B[3]), .A1 (n_8), .B0 (n_11), .B1 (A[5]), .Y
       (n_49));
  AOI22XL g2494(.A0 (n_5), .A1 (A[5]), .B0 (B[5]), .B1 (n_8), .Y
       (n_48));
  AOI22XL g2495(.A0 (n_5), .A1 (A[2]), .B0 (B[5]), .B1 (n_10), .Y
       (n_47));
  AOI22XL g2496(.A0 (n_5), .A1 (A[1]), .B0 (B[5]), .B1 (n_2), .Y
       (n_46));
  AOI22XL g2497(.A0 (n_5), .A1 (A[3]), .B0 (B[5]), .B1 (n_4), .Y
       (n_45));
  AOI22XL g2498(.A0 (n_5), .A1 (A[6]), .B0 (B[5]), .B1 (n_14), .Y
       (n_44));
  AOI22XL g2499(.A0 (n_5), .A1 (A[4]), .B0 (B[5]), .B1 (n_9), .Y
       (n_43));
  OAI22XL g2500(.A0 (B[7]), .A1 (n_8), .B0 (n_12), .B1 (A[5]), .Y
       (n_42));
  OAI22XL g2501(.A0 (B[7]), .A1 (n_4), .B0 (n_12), .B1 (A[3]), .Y
       (n_41));
  OAI22XL g2502(.A0 (B[7]), .A1 (n_9), .B0 (n_12), .B1 (A[4]), .Y
       (n_40));
  OAI22XL g2503(.A0 (B[7]), .A1 (n_2), .B0 (n_12), .B1 (A[1]), .Y
       (n_39));
  OAI22XL g2504(.A0 (B[7]), .A1 (n_10), .B0 (n_12), .B1 (A[2]), .Y
       (n_38));
  OAI22XL g2505(.A0 (B[7]), .A1 (n_14), .B0 (n_12), .B1 (A[6]), .Y
       (n_37));
  OAI22XL g2506(.A0 (B[3]), .A1 (n_13), .B0 (n_11), .B1 (A[0]), .Y
       (n_36));
  AOI22XL g2507(.A0 (n_5), .A1 (A[0]), .B0 (B[5]), .B1 (n_13), .Y
       (n_35));
  OAI22XL g2508(.A0 (B[7]), .A1 (n_13), .B0 (n_12), .B1 (A[0]), .Y
       (n_34));
  OR2X1 g2509(.A (n_3), .B (A[12]), .Y (n_33));
  NOR2XL g2510(.A (n_3), .B (A[14]), .Y (n_32));
  OR2X1 g2511(.A (n_3), .B (A[10]), .Y (n_31));
  NOR2XL g2512(.A (B[4]), .B (A[0]), .Y (n_30));
  OR2X1 g2513(.A (n_3), .B (A[13]), .Y (n_29));
  OR2X1 g2514(.A (n_3), .B (A[11]), .Y (n_28));
  NOR2XL g2515(.A (B[6]), .B (A[0]), .Y (n_27));
  NOR2XL g2516(.A (B[2]), .B (A[0]), .Y (n_26));
  NAND2XL g2517(.A (B[1]), .B (n_15), .Y (n_25));
  NAND2XL g2518(.A (B[1]), .B (n_7), .Y (n_24));
  NAND2XL g2519(.A (B[1]), .B (n_6), .Y (n_23));
  NAND2XL g2520(.A (B[1]), .B (n_14), .Y (n_22));
  NAND2XL g2521(.A (B[1]), .B (n_8), .Y (n_21));
  NAND2XL g2522(.A (B[1]), .B (n_10), .Y (n_20));
  NAND2XL g2523(.A (B[1]), .B (n_4), .Y (n_19));
  NAND2XL g2524(.A (B[1]), .B (n_9), .Y (n_18));
  NAND2XL g2525(.A (B[1]), .B (n_2), .Y (n_17));
  NAND2XL g2526(.A (B[1]), .B (n_13), .Y (n_16));
  INVX1 g2527(.A (A[8]), .Y (n_15));
  INVX1 g2528(.A (A[6]), .Y (n_14));
  INVX1 g2529(.A (A[0]), .Y (n_13));
  INVX1 g2530(.A (B[7]), .Y (n_12));
  INVX1 g2531(.A (B[3]), .Y (n_11));
  INVX1 g2532(.A (A[2]), .Y (n_10));
  INVX1 g2533(.A (A[4]), .Y (n_9));
  INVX1 g2534(.A (A[5]), .Y (n_8));
  INVX1 g2535(.A (A[9]), .Y (n_7));
  INVX1 g2536(.A (A[7]), .Y (n_6));
  INVX1 g2537(.A (B[5]), .Y (n_5));
  INVX1 g2538(.A (A[3]), .Y (n_4));
  INVX1 g2539(.A (B[1]), .Y (n_3));
  INVX1 g2540(.A (A[1]), .Y (n_2));
  NAND2BX1 g2(.AN (n_72), .B (A[0]), .Y (n_0));
  TIELO tie_0_cell(.Y (Z[0]));
endmodule

module fsm(clk, reset, power_btn, mode_inc, mode_dec, fstop_inc,
     fstop_dec, shutter_inc, shutter_dec, shutter_btn, sensor_data,
     output_data, output_data_valid);
  input clk, reset, power_btn, mode_inc, mode_dec, fstop_inc,
       fstop_dec, shutter_inc, shutter_dec, shutter_btn;
  input [15:0] sensor_data;
  output [15:0] output_data;
  output output_data_valid;
  wire clk, reset, power_btn, mode_inc, mode_dec, fstop_inc, fstop_dec,
       shutter_inc, shutter_dec, shutter_btn;
  wire [15:0] sensor_data;
  wire [15:0] output_data;
  wire output_data_valid;
  wire [2:0] aperture_setting;
  wire [7:0] shutter_setting_output;
  wire [7:0] aperture_multiplier;
  wire [2:0] shutter_setting;
  wire [3:0] current_state;
  wire [3:0] prev_mode_state;
  wire UNCONNECTED, UNCONNECTED0, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_87, n_88;
  wire n_89, n_90, n_91, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_173, n_174, power_on, scd_done;
  dffs_WIDTH3 APERTURE_SETTING_FF(.d ({n_113, n_112, n_111}), .q
       (aperture_setting), .en (n_114), .clk (clk), .rst (reset));
  countdown COUNTDOWN_MODULE(.clk (clk), .reset (n_89), .wait_cycles
       ({shutter_setting_output, output_data[0]}), .write_enable
       (n_88), .countdown_enable (n_90), .done (scd_done));
  aperture_decoder FSTOP_DECODER(.input_setting (aperture_setting),
       .output_multiplier (aperture_multiplier));
  shutter_decoder SHUTTER_DECODER(.input_setting (shutter_setting),
       .shutter_wait_time (shutter_setting_output));
  dffs_WIDTH3_61 SHUTTER_SETTING_FF(.d ({n_110, n_109, n_108}), .q
       (shutter_setting), .en (n_87), .clk (clk), .rst (reset));
  mult_unsigned mul_261_30(.A ({output_data[0], sensor_data[14:0]}), .B
       (aperture_multiplier), .Z ({n_116, n_117, n_118, n_119, n_120,
       n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129,
       n_130, n_131}));
  mult_unsigned_197 mul_261_52(.A ({output_data[0], n_117, n_118,
       n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127,
       n_128, n_129, n_130, n_131}), .B ({shutter_setting_output,
       output_data[0]}), .Z ({n_154, n_155, n_156, n_157, n_158, n_159,
       n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168,
       UNCONNECTED}));
  OAI222XL g2431(.A0 (n_71), .A1 (n_82), .B0 (n_72), .B1 (n_83), .C0
       (aperture_setting[1]), .C1 (n_173), .Y (n_109));
  OAI222XL g2432(.A0 (n_73), .A1 (n_81), .B0 (n_74), .B1 (n_80), .C0
       (shutter_setting[1]), .C1 (n_115), .Y (n_112));
  OAI222XL g2433(.A0 (n_75), .A1 (n_81), .B0 (shutter_setting[2]), .B1
       (n_115), .C0 (n_77), .C1 (n_80), .Y (n_113));
  OAI222XL g2434(.A0 (n_76), .A1 (n_82), .B0 (aperture_setting[2]), .B1
       (n_173), .C0 (n_78), .C1 (n_83), .Y (n_110));
  OAI22XL g2435(.A0 (aperture_setting[0]), .A1 (n_85), .B0
       (shutter_setting[0]), .B1 (n_115), .Y (n_111));
  OAI22XL g2436(.A0 (shutter_setting[0]), .A1 (n_84), .B0
       (aperture_setting[0]), .B1 (n_173), .Y (n_108));
  NAND2XL g2437(.A (n_115), .B (n_85), .Y (n_114));
  NAND2XL g2438(.A (n_173), .B (n_84), .Y (n_87));
  NAND3XL g2439(.A (n_115), .B (n_91), .C (n_79), .Y (n_88));
  AND2XL g2440(.A (output_data_valid), .B (n_154), .Y
       (output_data[15]));
  AND2XL g2441(.A (output_data_valid), .B (n_166), .Y (output_data[3]));
  AND2XL g2442(.A (output_data_valid), .B (n_158), .Y
       (output_data[11]));
  AND2XL g2443(.A (output_data_valid), .B (n_167), .Y (output_data[2]));
  AND2XL g2444(.A (output_data_valid), .B (n_159), .Y
       (output_data[10]));
  AND2XL g2445(.A (output_data_valid), .B (n_168), .Y (output_data[1]));
  AND2XL g2446(.A (output_data_valid), .B (n_155), .Y
       (output_data[14]));
  AND2XL g2447(.A (output_data_valid), .B (n_160), .Y (output_data[9]));
  AND2X1 g2448(.A (n_80), .B (n_81), .Y (n_85));
  AND2XL g2449(.A (output_data_valid), .B (n_161), .Y (output_data[8]));
  AND2XL g2450(.A (output_data_valid), .B (n_162), .Y (output_data[7]));
  AND2XL g2451(.A (output_data_valid), .B (n_163), .Y (output_data[6]));
  AND2X1 g2452(.A (n_83), .B (n_82), .Y (n_84));
  AND2XL g2453(.A (output_data_valid), .B (n_156), .Y
       (output_data[13]));
  AND2XL g2454(.A (output_data_valid), .B (n_157), .Y
       (output_data[12]));
  AND2XL g2455(.A (output_data_valid), .B (n_164), .Y (output_data[5]));
  AND2XL g2456(.A (output_data_valid), .B (n_165), .Y (output_data[4]));
  NOR3BXL g2457(.AN (current_state[3]), .B (current_state[0]), .C
       (n_62), .Y (n_90));
  NAND3XL g2458(.A (current_state[2]), .B (current_state[1]), .C
       (n_66), .Y (n_83));
  NAND3XL g2459(.A (current_state[2]), .B (current_state[1]), .C
       (n_69), .Y (n_82));
  NOR3BX1 g2460(.AN (current_state[3]), .B (n_6), .C (n_62), .Y
       (output_data_valid));
  NAND3BXL g2461(.AN (current_state[1]), .B (current_state[2]), .C
       (n_69), .Y (n_81));
  NAND3BXL g2462(.AN (current_state[1]), .B (current_state[2]), .C
       (n_66), .Y (n_80));
  NAND3XL g2463(.A (current_state[3]), .B (n_6), .C (n_68), .Y (n_79));
  CLKXOR2X1 g2464(.A (shutter_setting[2]), .B (n_67), .Y (n_78));
  CLKXOR2X1 g2465(.A (aperture_setting[2]), .B (n_64), .Y (n_77));
  XNOR2X1 g2466(.A (shutter_setting[2]), .B (n_65), .Y (n_76));
  XNOR2X1 g2467(.A (aperture_setting[2]), .B (n_70), .Y (n_75));
  INVX1 g2468(.A (n_73), .Y (n_74));
  NOR2BX1 g2469(.AN (n_64), .B (n_70), .Y (n_73));
  NAND2BXL g2470(.AN (n_62), .B (n_66), .Y (n_115));
  INVX1 g2471(.A (n_71), .Y (n_72));
  NOR2BX1 g2472(.AN (n_67), .B (n_65), .Y (n_71));
  AND2X1 g2473(.A (n_68), .B (n_66), .Y (n_89));
  NAND2XL g2474(.A (n_68), .B (n_69), .Y (n_173));
  NAND2BXL g2475(.AN (n_62), .B (n_69), .Y (n_91));
  NOR2XL g2476(.A (aperture_setting[1]), .B (aperture_setting[0]), .Y
       (n_70));
  NOR2XL g2477(.A (current_state[3]), .B (n_6), .Y (n_69));
  NOR2XL g2478(.A (current_state[1]), .B (current_state[2]), .Y (n_68));
  NAND2XL g2479(.A (shutter_setting[1]), .B (shutter_setting[0]), .Y
       (n_67));
  NOR2XL g2480(.A (current_state[0]), .B (current_state[3]), .Y (n_66));
  NOR2XL g2481(.A (shutter_setting[1]), .B (shutter_setting[0]), .Y
       (n_65));
  NAND2XL g2482(.A (aperture_setting[1]), .B (aperture_setting[0]), .Y
       (n_64));
  NAND2BX1 g2(.AN (current_state[2]), .B (current_state[1]), .Y (n_62));
  DFFRX1 power_on_reg(.RN (n_4), .CK (power_btn), .D (power_on), .Q
       (UNCONNECTED0), .QN (power_on));
  DFFSHQX1 \prev_mode_state_reg[0] (.SN (n_4), .CK (clk), .D (n_30), .Q
       (prev_mode_state[0]));
  SDFFRHQX1 \prev_mode_state_reg[1] (.RN (n_4), .CK (clk), .D
       (prev_mode_state[1]), .SI (current_state[1]), .SE (n_19), .Q
       (prev_mode_state[1]));
  OAI211X1 g2809(.A0 (current_state[2]), .A1 (n_41), .B0 (n_52), .C0
       (n_59), .Y (n_61));
  OAI211X1 g2810(.A0 (n_2), .A1 (n_16), .B0 (n_31), .C0 (n_58), .Y
       (n_60));
  AOI21XL g2812(.A0 (prev_mode_state[0]), .A1 (n_24), .B0 (n_57), .Y
       (n_59));
  AOI22XL g2813(.A0 (n_11), .A1 (n_55), .B0 (prev_mode_state[1]), .B1
       (n_9), .Y (n_58));
  AOI211XL g2814(.A0 (current_state[0]), .A1 (n_54), .B0 (n_29), .C0
       (n_48), .Y (n_57));
  OAI211X1 g2815(.A0 (n_29), .A1 (n_53), .B0 (n_16), .C0 (n_22), .Y
       (n_56));
  OAI222XL g2816(.A0 (n_5), .A1 (n_40), .B0 (current_state[2]), .B1
       (n_51), .C0 (n_23), .C1 (n_32), .Y (n_55));
  NAND2XL g2818(.A (n_26), .B (n_49), .Y (n_54));
  AOI32X1 g2819(.A0 (shutter_btn), .A1 (current_state[0]), .A2 (n_45),
       .B0 (n_23), .B1 (n_42), .Y (n_53));
  AOI22XL g2820(.A0 (n_21), .A1 (n_47), .B0 (current_state[0]), .B1
       (n_15), .Y (n_52));
  NAND2XL g2821(.A (n_14), .B (n_46), .Y (n_51));
  OAI21XL g2822(.A0 (n_29), .A1 (n_44), .B0 (n_16), .Y (n_50));
  OAI221X1 g2823(.A0 (n_2), .A1 (n_38), .B0 (shutter_btn), .B1 (n_36),
       .C0 (n_25), .Y (n_49));
  OAI33X1 g2824(.A0 (n_7), .A1 (n_34), .A2 (n_37), .B0
       (current_state[1]), .B1 (prev_mode_state[0]), .B2
       (current_state[0]), .Y (n_48));
  OAI21XL g2825(.A0 (n_5), .A1 (n_2), .B0 (n_43), .Y (n_47));
  OAI222XL g2826(.A0 (n_7), .A1 (n_42), .B0 (n_10), .B1 (n_35), .C0
       (current_state[1]), .C1 (n_12), .Y (n_46));
  NOR2XL g2827(.A (n_35), .B (n_174), .Y (n_45));
  AOI21XL g2828(.A0 (current_state[0]), .A1 (n_35), .B0 (n_174), .Y
       (n_44));
  AOI33XL g2829(.A0 (mode_dec), .A1 (n_5), .A2 (n_17), .B0
       (prev_mode_state[0]), .B1 (n_13), .B2 (n_6), .Y (n_43));
  AND2X1 g2832(.A (n_34), .B (n_27), .Y (n_42));
  NAND3XL g2833(.A (current_state[3]), .B (n_23), .C (scd_done), .Y
       (n_41));
  NOR2BX1 g2834(.AN (n_12), .B (n_33), .Y (n_40));
  INVX1 g2836(.A (n_37), .Y (n_38));
  OAI22XL g2837(.A0 (shutter_inc), .A1 (n_27), .B0 (n_3), .B1 (n_20),
       .Y (n_37));
  NOR2XL g2838(.A (n_2), .B (n_28), .Y (n_36));
  NAND2XL g2839(.A (n_26), .B (n_25), .Y (n_35));
  AND2X1 g2840(.A (n_28), .B (shutter_btn), .Y (n_34));
  NOR2BX1 g2841(.AN (n_17), .B (current_state[2]), .Y (n_33));
  OAI211X1 g2842(.A0 (prev_mode_state[1]), .A1 (n_8), .B0 (mode_dec),
       .C0 (n_5), .Y (n_32));
  OAI211X1 g2843(.A0 (prev_mode_state[1]), .A1 (n_10), .B0
       (current_state[3]), .C0 (n_1), .Y (n_31));
  MX2X1 g2844(.A (prev_mode_state[0]), .B (current_state[0]), .S0
       (n_19), .Y (n_30));
  NAND2XL g2845(.A (n_14), .B (n_21), .Y (n_29));
  NAND2XL g2846(.A (shutter_inc), .B (n_20), .Y (n_28));
  OAI31X1 g2847(.A0 (shutter_setting[0]), .A1 (shutter_setting[2]), .A2
       (shutter_setting[1]), .B0 (shutter_dec), .Y (n_27));
  NAND2XL g2848(.A (fstop_inc), .B (n_18), .Y (n_26));
  OAI31X1 g2849(.A0 (aperture_setting[0]), .A1 (aperture_setting[2]),
       .A2 (aperture_setting[1]), .B0 (fstop_dec), .Y (n_25));
  OAI22XL g2850(.A0 (n_0), .A1 (n_10), .B0 (current_state[3]), .B1
       (n_1), .Y (n_24));
  INVX1 g2851(.A (n_7), .Y (n_23));
  NAND2XL g2852(.A (current_state[3]), .B (n_10), .Y (n_22));
  AND2X1 g2853(.A (n_11), .B (n_1), .Y (n_21));
  NAND3XL g2854(.A (shutter_setting[2]), .B (shutter_setting[0]), .C
       (shutter_setting[1]), .Y (n_20));
  NAND3XL g2855(.A (n_91), .B (n_173), .C (n_115), .Y (n_19));
  NAND3XL g2856(.A (aperture_setting[0]), .B (aperture_setting[1]), .C
       (aperture_setting[2]), .Y (n_18));
  OAI21XL g2857(.A0 (current_state[1]), .A1 (n_6), .B0 (n_7), .Y
       (n_17));
  INVX1 g2859(.A (n_15), .Y (n_16));
  NOR2XL g2860(.A (n_0), .B (n_1), .Y (n_15));
  INVX1 g2861(.A (n_14), .Y (n_13));
  NOR2XL g2862(.A (mode_dec), .B (mode_inc), .Y (n_14));
  NAND2XL g2863(.A (prev_mode_state[1]), .B (n_6), .Y (n_12));
  NOR2XL g2864(.A (current_state[3]), .B (power_on), .Y (n_11));
  NAND2XL g2865(.A (current_state[1]), .B (current_state[0]), .Y
       (n_10));
  NOR2XL g2866(.A (current_state[3]), .B (n_1), .Y (n_9));
  NOR2XL g2867(.A (current_state[2]), .B (n_6), .Y (n_8));
  NAND2XL g2868(.A (current_state[1]), .B (n_6), .Y (n_7));
  INVX1 g2870(.A (mode_inc), .Y (n_5));
  INVX1 g2871(.A (reset), .Y (n_4));
  INVX1 g2872(.A (shutter_dec), .Y (n_3));
  AOI21X1 g2876(.A0 (n_27), .A1 (n_28), .B0 (n_2), .Y (n_174));
  DFFRX1 \current_state_reg[0] (.RN (n_4), .CK (clk), .D (n_61), .Q
       (current_state[0]), .QN (n_6));
  DFFRX1 \current_state_reg[1] (.RN (n_4), .CK (clk), .D (n_60), .Q
       (current_state[1]), .QN (n_2));
  DFFRX1 \current_state_reg[2] (.RN (n_4), .CK (clk), .D (n_50), .Q
       (current_state[2]), .QN (n_1));
  DFFRX1 \current_state_reg[3] (.RN (n_4), .CK (clk), .D (n_56), .Q
       (current_state[3]), .QN (n_0));
  TIELO tie_0_cell(.Y (output_data[0]));
endmodule

